todoapp/urls.py
from . import views
from django.urls import path

app_name = 'todoapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<int:taskid>', views.delete,name='delete'),
    path('update/<int:id>', views.update, name='update'),
    path('cbvhome/', views.TaskListview.as_view(), name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.TaskDetailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.TaskUpdateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.TaskDeleteview.as_view(),name='cbvdelete'),
]

todoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

todoapp/models.py
from django.db import models


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=250)
    priority = models.IntegerField()
    date = models.DateField()

    def __str__(self):
        return self.name

todoapp/forms.py
from django import forms
from .models import Task


class TodoForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'priority', 'date']

todoapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from . models import Task
from . forms import TodoForm
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView


class TaskListview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'


class TaskDetailview(DetailView):
    model = Task
    template_name = 'detail.html'
    context_object_name = 'task'


class TaskUpdateview(UpdateView):
    model = Task
    template_name = 'edit.html'
    context_object_name = 'task'
    fields = ('name', 'priority', 'date')

    def get_success_url(self):
        return reverse_lazy('todoapp:cbvdetail', kwargs={'pk': self.object.id})

class TaskDeleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todoapp:cbvhome')


# Create your views here.
def home(request):
    task1 = Task.objects.all()
    if request.method == 'POST':
        name = request.POST.get('task', '')
        priority = request.POST.get('priority', '')
        date = request.POST.get('date', '')
        task = Task(name=name, priority=priority, date=date)
        task.save()
        return redirect('/')
    return render(request, 'home.html', {'task1': task1})


def detail(request):
    task = Task.objects.all()
    return render(request, 'detail.html', {'task': task})


def delete(request, taskid):
    if request.method == 'POST':
        task = Task.objects.get(id=taskid)
        task.delete()
        return redirect('/')
    return render(request, 'delete.html')


def update(request, id):
    task = Task.objects.get(id=id)
    form = TodoForm(request.POST or None, instance=task)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'update.html', {'task': task, 'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">
    {% csrf_token %}
    <p>Are you sure this task is done?</p>
    <button type="submit">confirm</button>
</form>

templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="card shadow">
    <div class="card-body">
        <h5>{{task.name}}</h5>
        <p><b>{{task.priority}}</b></p>
        <p>{{task.date}}</p>
        <a class="btn btn-danger" href="{% url 'todoapp:delete' task.id %}">done</a>
        <a class="btn btn-warning" href="{% url 'todoapp:update' task.id %}">update</a>
    </div>
</div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<div class="card">
    <div class="card-header">
        <div class="card-title">
            Task Update
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">confirm</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <form method="POST" class="p-3 shadow">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="task" class="form-control" placeholder="Enter task name">
                </div>
                <div class="form-group">
                    <input type="text" name="priority" class="form-control" placeholder="Enter your priority">
                </div>
                <div class="form-group">
                    <input type="date" name="date" class="form-control" placeholder="Enter your date">
                </div>
                <input type="submit" class="btn btn-success">
            </form>
        </div>
        <div class="col-md-6">
            <h3>Task to be completed</h3>
            {% for i in task1 %}
            <div class="card shadow">
                <div class="card-body">
                    <h5>{{i.name}}</h5>
                    <p><b>{{i.priority}}</b></p>
                    <p>{{i.date}}</p>
                    <a class="btn btn-danger" href="{% url 'todoapp:delete' i.id %}">done</a>
                    <a class="btn btn-warning" href="{% url 'todoapp:update' i.id %}">update</a>
                </div>
            </div><br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">confirm</button>
</form>

{% endblock %}